var mainVm = new Vue({
    el: '#app',
    data: {
        floor: {
            group1:{ 
                description: 'Non-Acrobatic Skills',
                group1Points: .5,
                A:{
                    letterValue: 'A',
                    AValue: .1,
                    skills:[{
                        name:'Handstand to L-sit',
                        description:'From handstand lower to L-sit or stradle L-sit',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 //all the same for A
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                             //all same: If (groupPoints){groupPoints = groupoints + 0} else {groupPoints = .5}
                        totalPoints: 0,                                                         //valuePoints + groupPoints
                        pic:'',
                        reference:'',
                    },
                    {   name:'Press handstand from stand',
                        description:'From stand, Swiss press to handstand (2s.)',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                 
                        pic:'',
                        reference:'',
                    },
                    {   name:'Handstand',
                        description:'Handstand (2 s.)',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Stradle Planche',
                        description:'Support lever, legs straddle (2 s.)',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Handstand Pirouette',
                        description:'1/2 or 1/1 turn in handstand or to handstand',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'',
                        description:'From L-sit, etc., turn over backward to stand',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Back Walkover',
                        description:'From stand or rear support, push off 1 foot through handstand',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Forward Walkover',
                        description:'',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Splits',
                        description:'Cross or side split (stop required)',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Scale',
                        description:'Any Standing Scale (2 s.)',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Jump backward to front support',
                        description:'Jump backward to front support',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Butterfly',
                        description:'Butterfly',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Breakdance Variation',
                        description:'Breakdance Variation',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Flair with 1/2 Spindle',
                        description:'Flair with 1/2 Spindle',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Russian',
                        description:'Russian wendeswing with 360 or 540',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Backward Roll 1/2 turn',
                        description:'Roll bwd. through handstand with 1/2 turn',
                        value:this.floor.group1.A.letterValue,
                        valuePoints:this.floor.group1.A.AValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    }]
                },
                B:{
                    letterValue: 'B',
                    BValue: .2,
                    skills:[{
                        name:'V-sit',
                        description:'V-sit (2 s.)',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Press Handstand',
                        description:'Piked body straight arm or straight body, bent arm press to handstand with legs together',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Press Handstand',
                        description:'Swiss press from split, L-sit, stradle L-sit or front support (2 s.)',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Japanese Handstand',
                        description:'Press or lower or swing to Japanese handstand',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Planche',
                        description:'Support lever (2 s.)',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Straddle Planche Press Handstand',
                        description:'From straddled support lever (2 s.) press handstand (2 s.)',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Stalder Roll Press Handstand',
                        description:'Endo Roll to handstand (2 s.)',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Scale',
                        description:'Any standing scale with 180 straddle, no hand. hold (2 s.)',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Endo',
                        description:'Jump backward with pike-stretch or with 1/1 turn to front support',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Tong Fei',
                        description:'Butterfly with 1/1 twist forward or backward',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Flair handstand',
                        description:'Circles or flair to handstand',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Handstand to flair',
                        description:'Lower from handstand to flair or circle',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Spindle Flair',
                        description:'Flair with 1/1 spindle (in 2 circles)',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Flair 1/2 spindle to handstand',
                        description:'Flair with 1/2 spindle to handstand',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'Russian',
                        description:'Russian wendeswing with 720 or 900',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {   name:'',
                        description:'Roll backward with 1/1 turn through handstand',
                        value:this.floor.group1.B.letterValue,
                        valuePoints:this.floor.group1.B.BValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    }]
                },
                C:{
                    letterValue: 'C',
                    CValue: .3,
                    skills:[{
                        name:'Manna',
                        description:'V-sit with legs horiz (2 s.)',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'V straddle press handstand',
                        description:'V-sit (2 s.) and press to handstand (2 s.) also with straddle legs',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Press Japanese handstand',
                        description:'From split press to Japanese handstand (2 s.)',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Swallow',
                        description:'Swallow (2 s.)',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Planche Press handstand',
                        description:'From support lever (2 s.) press handstand (2 s.)',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Stadle roll press handstand',
                        description:'Endo roll piked to handstand (2 s.), also final phase with straddle',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Butterfly',
                        description:'Butterfly with 2/1 twist',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Gogoladze',
                        description:'Flair or circle to handstand continue to flair or circle',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Spindle Flair to handstand',
                        description:'Flair with 270 spindle (in 2 circles) directly to handstand',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Fedorchenko',
                        description:'Russian wendeswing with 1080 or more',
                        value:this.floor.group1.C.letterValue,
                        valuePoints:this.floor.group1.C.CValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    }]
                },
                D:{
                    letterValue: 'D',
                    DValue: .4,
                    skills:[{
                        name:'Manna press handstand',
                        description:'Manna (2 s.) and press to handstand (2 s.) also with straddle legs',
                        value:this.floor.group1.D.letterValue,
                        valuePoints:this.floor.group1.D.DValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Manna dislocate to handstand',
                        description:'Manna (2 s.) turn over to handstand (2 s.)',
                        value:this.floor.group1.D.letterValue,
                        valuePoints:this.floor.group1.D.DValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Alvarino',
                        description:'From Swallow (2 s.) press to Japanese handstand (2 s.)',
                        value:this.floor.group1.D.letterValue,
                        valuePoints:this.floor.group1.D.DValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Air Flair',
                        description:'Flair hopping with 360 turn backwards through handstand and back to flair (2 hops)',
                        value:this.floor.group1.D.letterValue,
                        valuePoints:this.floor.group1.D.DValue,                                 
                        group:'Group 1',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Spindle flair to handstand to flair',
                        description:'Flair with 270 spindle (in 2 circles) directly to handstand and continue to circle flair',
                        value:this.floor.group1.D.letterValue,
                        valuePoints:this.floor.group1.D.DValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Manna press handstand',
                        description:'Manna (2 s.) and press to handstand (2 s.) also with straddle legs',
                        value:this.floor.group1.D.letterValue,
                        valuePoints:this.floor.group1.D.DValue,                                 
                        group:'Group I',
                        groupDescription:this.floor.group1.description,     
                        groupPoints:this.floor.group1.group1points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    }]
                }
            },
            group2:{ 
                description: 'Front Salto Skills',
                group2Points: .5,
                A:{
                    letterValue: 'A',
                    AValue: .1,
                    skills:[{
                        name:'',
                        description:'Neck or headspring with 1/2 turn to handstand or 1/1 turn to rear support',
                        value:this.floor.group2.A.letterValue,
                        valuePoints:this.floor.group2.A.AValue, 
                        group: 'Group II',                              
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Front handspring or flyspring',
                        description:'Front handspring or flyspring',
                        value:this.floor.group2.A.letterValue,
                        valuePoints:this.floor.group2.A.AValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Dive roll',
                        description:'Dive Roll',
                        value:this.floor.group2.A.letterValue,
                        valuePoints:this.floor.group2.A.AValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Front tuck or pike',
                        description:'Salto forward tucked or piked',
                        value:this.floor.group2.A.letterValue,
                        valuePoints:this.floor.group2.A.AValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Aerial walkover forward',
                        description:'Aerial Walkover forward',
                        value:this.floor.group2.A.letterValue,
                        valuePoints:this.floor.group2.A.AValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Front flip 1/2 turn',
                        description:'Salto tucked and piked 1/2 turn',
                        value:this.floor.group2.A.letterValue,
                        valuePoints:this.floor.group2.A.AValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    }]
                },
                B:{
                    letterValue: 'B',
                    BValue: .2,
                    skills:[{
                        name:'1/1 twisting forward handspring',
                        description:'Jump with 1/1 twist to forward handspring',
                        value:this.floor.group2.B.letterValue,
                        valuePoints:this.floor.group2.B.BValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Front layout',
                        description:'Salto forward stretched',
                        value:this.floor.group2.B.letterValue,
                        valuePoints:this.floor.group2.B.BValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Front full',
                        description:'Salto tucked with 1/1 turn',
                        value:this.floor.group2.B.letterValue,
                        valuePoints:this.floor.group2.B.BValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Branny layout',
                        description:'Salto forward stretched with 1/2 turn',
                        value:this.floor.group2.B.letterValue,
                        valuePoints:this.floor.group2.B.BValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Rudy tucked',
                        description:'Salto tucked 3/2 turn',
                        value:this.floor.group2.B.letterValue,
                        valuePoints:this.floor.group2.B.BValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Front 1 and 1/4',
                        description:'Salto forward tucked or piked to front support',
                        value:this.floor.group2.B.letterValue,
                        valuePoints:this.floor.group2.B.BValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                C:{
                    letterValue: 'C',
                    CValue: .3,
                    skills: [{
                        name:'Front 1 and 1/4 layout',
                        description:'Salto forward stretched to front support',
                        value:this.floor.group2.C.letterValue,
                        valuePoints:this.floor.group2.C.CValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Front full layout',
                        description:'Salto forward stretched with 1/1 turn',
                        value:this.floor.group2.C.letterValue,
                        valuePoints:this.floor.group2.C.CValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Layout Rudy',
                        description:'Salto forward stretched with 3/2 turn',
                        value:this.floor.group2.C.letterValue,
                        valuePoints:this.floor.group2.C.CValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Front full 1 and 1/4',
                        description:'Salto forward in any position with full turn to front support',
                        value:this.floor.group2.C.letterValue,
                        valuePoints:this.floor.group2.C.CValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                D:{
                    letterValue: 'D',
                    DValue: .4,
                    skills: [{
                        name:'Morandi',
                        description:'Hanspring salto forward tucked (Marinich style)',
                        value:this.floor.group2.D.letterValue,
                        valuePoints:this.floor.group2.D.DValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Double front',
                        description:'Double salto forward tucked',
                        value:this.floor.group2.D.letterValue,
                        valuePoints:this.floor.group2.D.DValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Front double full',
                        description:'Salto forward stretched with 2/1 turn',
                        value:this.floor.group2.D.letterValue,
                        valuePoints:this.floor.group2.D.DValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Defer',
                        description:'Jump forward with 1/2 turn to double salto backward tucked or piked',
                        value:this.floor.group2.D.letterValue,
                        valuePoints:this.floor.group2.D.DValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                E:{
                    letterValue: 'E',
                    EValue: .5,
                    skills: [{
                        name:'Front double pike',
                        description:'Double salto forward piked',
                        value:this.floor.group2.E.letterValue,
                        valuePoints:this.floor.group2.E.EValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Double front half',
                        description:'Double salto forward tucked with 1/2 turn',
                        value:this.floor.group2.E.letterValue,
                        valuePoints:this.floor.group2.E.EValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Randy',
                        description:'Double salto forward piked',
                        value:this.floor.group2.E.letterValue,
                        valuePoints:this.floor.group2.E.EValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                F:{
                    letterValue: 'F',
                    FValue: .6,
                    skills: [{
                        name:'Double pike half',
                        description:'Double salto forward piked with 1/2 turn',
                        value:this.floor.group2.F.letterValue,
                        valuePoints:this.floor.group2.F.FValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Shirai 2',
                        description:'Salto forward stretched with 3/1 turn',
                        value:this.floor.group2.F.letterValue,
                        valuePoints:this.floor.group2.F.FValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Full twisting double front',
                        description:'Double salto forward with 1/1 turn tucked',
                        value:this.floor.group2.F.letterValue,
                        valuePoints:this.floor.group2.F.FValue,                                 
                        group: 'Group II',
                        groupDescription:this.floor.group2.description,     
                        groupPoints:this.floor.group2.group2points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                }
            },
            group3:{ 
                description: 'Back Salto Skills',
                group3Points: .5,
                A:{
                    letterValue: 'A',
                    AValue: .1,
                    skills:[{
                        name:'Back tuck or pike',
                        description:'Salto backward tucked or piked',
                        value:this.floor.group3.A.letterValue,
                        valuePoints:this.floor.group3.A.AValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',

                    },
                    {
                        name:'Back half tuck or pike',
                        description:'Salto backward tucked or piked with 1/2 turn',
                        value:this.floor.group3.A.letterValue,
                        valuePoints:this.floor.group3.A.AValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Back handspring',
                        description:'Back handspring',
                        value:this.floor.group3.A.letterValue,
                        valuePoints:this.floor.group3.A.AValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Arabian dive roll',
                        description:'Jump backward with half turn to roll forward',
                        value:this.floor.group3.A.letterValue,
                        valuePoints:this.floor.group3.A.AValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    },
                    {
                        name:'Arabian front handspring',
                        description:'Jump backward with 1/2 turn to handspring forward',
                        value:this.floor.group3.A.letterValue,
                        valuePoints:this.floor.group3.A.AValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                    }]
                },
                B:{
                    letterValue: 'B',
                    BValue: .2,
                    skills:[{
                        name:'Back Layout',
                        description:'Salto backward stretched',
                        value:this.floor.group3.B.letterValue,
                        valuePoints:this.floor.group3.B.BValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Back Layout half',
                        description:'Salto backward stretched with half turn',
                        value:this.floor.group3.B.letterValue,
                        valuePoints:this.floor.group3.B.BValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Whip',
                        description:'Tempo salto backward',
                        value:this.floor.group3.B.letterValue,
                        valuePoints:this.floor.group3.B.BValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Back 3/2 tucked',
                        description:'Salto backward tucked with 3/2 turn',
                        value:this.floor.group3.B.letterValue,
                        valuePoints:this.floor.group3.B.BValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Layout full',
                        description:'Salto backward stretched with 1/1 turn',
                        value:this.floor.group3.B.letterValue,
                        valuePoints:this.floor.group3.B.BValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Arabian 1 and 1/4',
                        description:'Jump backward with 1/2 turn to salto forward tucked or piked to front support',
                        value:this.floor.group3.B.letterValue,
                        valuePoints:this.floor.group3.B.BValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                C:{
                    letterValue: 'C',
                    CValue: .3,
                    skills:[{
                        name:'Double back tuck',
                        description:'Double salto backward tucked',
                        value:this.floor.group3.C.letterValue,
                        valuePoints:this.floor.group3.C.CValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Double back pike',
                        description:'Double salto backward piked',
                        value:this.floor.group3.C.letterValue,
                        valuePoints:this.floor.group3.C.CValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Back 3/2 layout',
                        description:'Salto backward stretched with 3/2 turn',
                        value:this.floor.group3.C.letterValue,
                        valuePoints:this.floor.group3.C.CValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Double full layout',
                        description:'Salto backward stretched with 2/1 turn',
                        value:this.floor.group3.C.letterValue,
                        valuePoints:this.floor.group3.C.CValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                D:{
                    letterValue: 'D',
                    DValue: .4,
                    skills:[{
                        name:'Full twisting double back, Arabian double',
                        description:'Double salto backward tucked or piked with 1/1 turn. Also Arabian double tucked or piked 1/2 turn',
                        value:this.floor.group3.D.letterValue,
                        valuePoints:this.floor.group3.D.DValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Arabian double',
                        description:'Arabian double tucked or piked or double salto backward tucked or piked with 1/2 turn',
                        value:this.floor.group3.D.letterValue,
                        valuePoints:this.floor.group3.D.DValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Back two and a half layout',
                        description:'Salto backward stretched with 5/2 turn',
                        value:this.floor.group3.D.letterValue,
                        valuePoints:this.floor.group3.D.DValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {                   
                        name:'Back triple full',
                        description:'Salto backward stretched with 3/1 turn',
                        value:this.floor.group3.D.letterValue,
                        valuePoints:this.floor.group3.D.DValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {                   
                        name:'Double layout',
                        description:'Double salto backward stretched',
                        value:this.floor.group3.D.letterValue,
                        valuePoints:this.floor.group3.D.DValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                E:{
                    letterValue: 'E',
                    EValue: .5,
                    skills:[{
                        name:'Double double tuck',
                        description:'Double salto backward tucked with 2/1 turn',
                        value:this.floor.group3.E.letterValue,
                        valuePoints:this.floor.group3.E.EValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Double back 3/2',
                        description:'Double salto backward tucked with 3/2 turn',
                        value:this.floor.group3.E.letterValue,
                        valuePoints:this.floor.group3.E.EValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Back 7/2',
                        description:'Salto backward stretched with 7/2 turn',
                        value:this.floor.group3.E.letterValue,
                        valuePoints:this.floor.group3.E.EValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Lou Yun',
                        description:'Double salto straddled with 1/1 turn',
                        value:this.floor.group3.E.letterValue,
                        valuePoints:this.floor.group3.E.EValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Double layout full',
                        description:'Double salto backward stretched with 1/1 turn or arabian jump backward to double salto forward stretched with 1/2 turn',
                        value:this.floor.group3.E.letterValue,
                        valuePoints:this.floor.group3.E.EValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                F:{
                    letterValue: 'F',
                    EValue: .6,
                    skills:[{
                        name:'Double 5/2 tuck',
                        description:'Double salto backward tuked with 5/2 turn',
                        value:this.floor.group3.F.letterValue,
                        valuePoints:this.floor.group3.F.FValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Shirai or Nguyen',
                        description:'Salto backward stretched with 4/1 turn',
                        value:this.floor.group3.F.letterValue,
                        valuePoints:this.floor.group3.F.FValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Kolyvanov',
                        description:'Salto backward stretched with 2/1 turn and salto backward piked',
                        value:this.floor.group3.F.letterValue,
                        valuePoints:this.floor.group3.F.FValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Arabian double layout full',
                        description:'Double salto backward stretched with 3/2 turn or Arabian jump backward to double salto forward stretched with 1/1 turn',
                        value:this.floor.group3.F.letterValue,
                        valuePoints:this.floor.group3.F.FValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Double double layout',
                        description:'Double salto backward stretched with 2/1 turn',
                        value:this.floor.group3.F.letterValue,
                        valuePoints:this.floor.group3.F.FValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                G:{
                    letterValue: 'G',
                    EValue: .7,
                    skills:[{
                        name:'Ri Jong Song',
                        description:'Double salto backward tucked with 3/1 turn',
                        value:this.floor.group3.G.letterValue,
                        valuePoints:this.floor.group3.G.GValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    },
                    {
                        name:'Double 5/2 layout',
                        description:'Double salto backward stretched with 5/2 turn',
                        value:this.floor.group3.G.letterValue,
                        valuePoints:this.floor.group3.G.GValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                },
                H:{
                    letterValue: 'H',
                    EValue: .8,
                    skills:[{
                        name:'Shirai 3',
                        description:'Double salto backward stretched with 3/1 turn',
                        value:this.floor.group3.H.letterValue,
                        valuePoints:this.floor.group3.H.HValue,
                        group: 'Group III',                                 
                        groupDescription:this.floor.group3.description,     
                        groupPoints:this.floor.group3.group3points,                                 
                        totalPoints: 0,                                     
                        pic:'',
                        reference:'',
                        connection: true
                    }]
                }
            }
        }
        // horse: {
  //        group1:{ 
  //            description: '',
  //            group1Points: .5,
  //            A:{
  //                AValue: .1,
  //                skills:[{
  //                    name:'',
  //                    description:'',
  //                    value:this.horse.group1.A,
  //                    valuePoints:this.horse.group1.A.AValue,                                 
  //                    group:'Group I',
  //                    groupDescription:this.horse.group1.description,     
  //                    groupPoints:this.horse.group1.group1points,                                 
  //                    totalPoints: 0,                                     
  //                    pic:,
  //                    reference:,
  //                }, 
    }
})